// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxxjf7Oh3wCpIx0Br4bCo0XQMa3jKMWqQ',
    appId: '1:122874069809:web:6614d58120f5e04db12610',
    messagingSenderId: '122874069809',
    projectId: 'vizinhacasolidaria-dc2c4',
    authDomain: 'vizinhacasolidaria-dc2c4.firebaseapp.com',
    storageBucket: 'vizinhacasolidaria-dc2c4.firebasestorage.app',
    measurementId: 'G-86MEK5Z53H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlLqinGjuTzC9ZwPPwyx3U7DySYBpoxVE',
    appId: '1:122874069809:android:2c7d58113424b6c8b12610',
    messagingSenderId: '122874069809',
    projectId: 'vizinhacasolidaria-dc2c4',
    storageBucket: 'vizinhacasolidaria-dc2c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDg9X7O7q-MA3vjZ8EqZFE80CPI7LZdLE',
    appId: '1:122874069809:ios:7d28cb5d13f391c3b12610',
    messagingSenderId: '122874069809',
    projectId: 'vizinhacasolidaria-dc2c4',
    storageBucket: 'vizinhacasolidaria-dc2c4.firebasestorage.app',
    iosBundleId: 'com.example.vizinhancaSolidaria.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDg9X7O7q-MA3vjZ8EqZFE80CPI7LZdLE',
    appId: '1:122874069809:ios:a84c7958444e6d3bb12610',
    messagingSenderId: '122874069809',
    projectId: 'vizinhacasolidaria-dc2c4',
    storageBucket: 'vizinhacasolidaria-dc2c4.firebasestorage.app',
    iosBundleId: 'com.example.vizinhancaSolidaria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxxjf7Oh3wCpIx0Br4bCo0XQMa3jKMWqQ',
    appId: '1:122874069809:web:e0d96ce5a8e7d3b5b12610',
    messagingSenderId: '122874069809',
    projectId: 'vizinhacasolidaria-dc2c4',
    authDomain: 'vizinhacasolidaria-dc2c4.firebaseapp.com',
    storageBucket: 'vizinhacasolidaria-dc2c4.firebasestorage.app',
    measurementId: 'G-WW515LFLNW',
  );
}
